[workspace]
members = ["macro_stub"]
# Keep archived projects out of the active workspace to avoid lockfile collisions
# with historical references.
exclude = ["archive/*"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["h4rm0n1c <h4rm0n1c@gmail.com>"]
version = "0.1.0"
